// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id,email,name,picture_url FROM users WHERE email=$1
`

type GetUserByEmailRow struct {
	ID         string
	Email      string
	Name       string
	PictureUrl string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
	)
	return i, err
}

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one
SELECT id,email,name,picture_url FROM users WHERE google_sub=$1
`

type GetUserByGoogleSubRow struct {
	ID         string
	Email      string
	Name       string
	PictureUrl string
}

func (q *Queries) GetUserByGoogleSub(ctx context.Context, googleSub pgtype.Text) (GetUserByGoogleSubRow, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSub, googleSub)
	var i GetUserByGoogleSubRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, picture_url FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID         string
	Email      string
	Name       string
	PictureUrl string
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
	)
	return i, err
}

const getUserIDByEmail = `-- name: GetUserIDByEmail :one
SELECT id FROM users WHERE email=$1
`

func (q *Queries) GetUserIDByEmail(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRow(ctx, getUserIDByEmail, email)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertPlaceholderUser = `-- name: InsertPlaceholderUser :exec
INSERT INTO users(id,email,name) VALUES($1,$2,'')
`

type InsertPlaceholderUserParams struct {
	ID    string
	Email string
}

func (q *Queries) InsertPlaceholderUser(ctx context.Context, arg InsertPlaceholderUserParams) error {
	_, err := q.db.Exec(ctx, insertPlaceholderUser, arg.ID, arg.Email)
	return err
}

const resolveCLIToken = `-- name: ResolveCLIToken :one
SELECT 'user'::text AS principal_type, u.id, u.email, u.name, u.picture_url
FROM cli_credentials c JOIN users u ON u.id=c.user_id
WHERE c.token_hash=$1 AND c.revoked_at IS NULL
`

type ResolveCLITokenRow struct {
	PrincipalType string
	ID            string
	Email         string
	Name          string
	PictureUrl    string
}

func (q *Queries) ResolveCLIToken(ctx context.Context, tokenHash string) (ResolveCLITokenRow, error) {
	row := q.db.QueryRow(ctx, resolveCLIToken, tokenHash)
	var i ResolveCLITokenRow
	err := row.Scan(
		&i.PrincipalType,
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
	)
	return i, err
}

const resolveServiceAccountToken = `-- name: ResolveServiceAccountToken :one
SELECT 'service_account'::text AS principal_type, sa.id, ''::text AS email, sa.name, ''::text AS picture_url
FROM service_account_keys k JOIN service_accounts sa ON sa.id=k.service_account_id
WHERE k.token_hash=$1 AND k.revoked_at IS NULL AND sa.disabled_at IS NULL
`

type ResolveServiceAccountTokenRow struct {
	PrincipalType string
	ID            string
	Email         string
	Name          string
	PictureUrl    string
}

func (q *Queries) ResolveServiceAccountToken(ctx context.Context, tokenHash string) (ResolveServiceAccountTokenRow, error) {
	row := q.db.QueryRow(ctx, resolveServiceAccountToken, tokenHash)
	var i ResolveServiceAccountTokenRow
	err := row.Scan(
		&i.PrincipalType,
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
	)
	return i, err
}

const touchCLIToken = `-- name: TouchCLIToken :exec
UPDATE cli_credentials SET last_used_at=now() WHERE token_hash=$1
`

func (q *Queries) TouchCLIToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, touchCLIToken, tokenHash)
	return err
}

const touchServiceAccountToken = `-- name: TouchServiceAccountToken :exec
UPDATE service_account_keys SET last_used_at=now() WHERE token_hash=$1
`

func (q *Queries) TouchServiceAccountToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, touchServiceAccountToken, tokenHash)
	return err
}

const upsertGoogleUser = `-- name: UpsertGoogleUser :exec
WITH updated AS (
  UPDATE users
  SET email=$2, name=$3, google_sub=$4, picture_url=$5
  WHERE google_sub=$4 OR (email=$2 AND google_sub IS NULL)
  RETURNING id
)
INSERT INTO users(id,email,name,google_sub,picture_url)
SELECT $1,$2,$3,$4,$5
WHERE NOT EXISTS (SELECT 1 FROM updated)
`

type UpsertGoogleUserParams struct {
	ID         string
	Email      string
	Name       string
	GoogleSub  pgtype.Text
	PictureUrl string
}

func (q *Queries) UpsertGoogleUser(ctx context.Context, arg UpsertGoogleUserParams) error {
	_, err := q.db.Exec(ctx, upsertGoogleUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.GoogleSub,
		arg.PictureUrl,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users(id,email,name) VALUES($1,$2,$3) ON CONFLICT(id) DO UPDATE SET email=EXCLUDED.email, name=EXCLUDED.name
`

type UpsertUserParams struct {
	ID    string
	Email string
	Name  string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser, arg.ID, arg.Email, arg.Name)
	return err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE id = $1)::bool
`

func (q *Queries) UserExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
