// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cli_credentials.sql

package dbsqlc

import (
	"context"
)

const createCLICredential = `-- name: CreateCLICredential :exec
INSERT INTO cli_credentials(id,user_id,name,token_hash) VALUES($1,$2,$3,$4)
`

type CreateCLICredentialParams struct {
	ID        string
	UserID    string
	Name      string
	TokenHash string
}

func (q *Queries) CreateCLICredential(ctx context.Context, arg CreateCLICredentialParams) error {
	_, err := q.db.Exec(ctx, createCLICredential,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
	)
	return err
}

const listCLICredentials = `-- name: ListCLICredentials :many
SELECT id,name FROM cli_credentials WHERE user_id=$1 AND revoked_at IS NULL ORDER BY created_at DESC
`

type ListCLICredentialsRow struct {
	ID   string
	Name string
}

func (q *Queries) ListCLICredentials(ctx context.Context, userID string) ([]ListCLICredentialsRow, error) {
	rows, err := q.db.Query(ctx, listCLICredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCLICredentialsRow
	for rows.Next() {
		var i ListCLICredentialsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCLICredential = `-- name: RevokeCLICredential :exec
UPDATE cli_credentials SET revoked_at=now() WHERE id=$1 AND user_id=$2
`

type RevokeCLICredentialParams struct {
	ID     string
	UserID string
}

func (q *Queries) RevokeCLICredential(ctx context.Context, arg RevokeCLICredentialParams) error {
	_, err := q.db.Exec(ctx, revokeCLICredential, arg.ID, arg.UserID)
	return err
}
