// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package dbsqlc

import (
	"context"
)

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id=$1
`

func (q *Queries) DeleteComment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, document_id, created_on_version_id, author_type, author_id, author_email, author_name, body, selected_text, anchor_json, status
FROM comments
WHERE id = $1
`

type GetCommentRow struct {
	ID                 string
	DocumentID         string
	CreatedOnVersionID string
	AuthorType         string
	AuthorID           string
	AuthorEmail        string
	AuthorName         string
	Body               string
	SelectedText       string
	AnchorJson         []byte
	Status             string
}

func (q *Queries) GetComment(ctx context.Context, id string) (GetCommentRow, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i GetCommentRow
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.CreatedOnVersionID,
		&i.AuthorType,
		&i.AuthorID,
		&i.AuthorEmail,
		&i.AuthorName,
		&i.Body,
		&i.SelectedText,
		&i.AnchorJson,
		&i.Status,
	)
	return i, err
}

const insertComment = `-- name: InsertComment :exec
INSERT INTO comments(id,document_id,created_on_version_id,author_type,author_id,author_email,author_name,body,selected_text,anchor_json,status)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'open')
`

type InsertCommentParams struct {
	ID                 string
	DocumentID         string
	CreatedOnVersionID string
	AuthorType         string
	AuthorID           string
	AuthorEmail        string
	AuthorName         string
	Body               string
	SelectedText       string
	AnchorJson         []byte
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) error {
	_, err := q.db.Exec(ctx, insertComment,
		arg.ID,
		arg.DocumentID,
		arg.CreatedOnVersionID,
		arg.AuthorType,
		arg.AuthorID,
		arg.AuthorEmail,
		arg.AuthorName,
		arg.Body,
		arg.SelectedText,
		arg.AnchorJson,
	)
	return err
}

const listComments = `-- name: ListComments :many
SELECT id,document_id,created_on_version_id,author_type,author_id,author_email,author_name,body,selected_text,anchor_json,status
FROM comments WHERE document_id=$1 AND ($2='' OR status=$2) AND ($3='' OR created_on_version_id=$3) ORDER BY created_at
`

type ListCommentsParams struct {
	DocumentID string
	Column2    interface{}
	Column3    interface{}
}

type ListCommentsRow struct {
	ID                 string
	DocumentID         string
	CreatedOnVersionID string
	AuthorType         string
	AuthorID           string
	AuthorEmail        string
	AuthorName         string
	Body               string
	SelectedText       string
	AnchorJson         []byte
	Status             string
}

func (q *Queries) ListComments(ctx context.Context, arg ListCommentsParams) ([]ListCommentsRow, error) {
	rows, err := q.db.Query(ctx, listComments, arg.DocumentID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsRow
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.CreatedOnVersionID,
			&i.AuthorType,
			&i.AuthorID,
			&i.AuthorEmail,
			&i.AuthorName,
			&i.Body,
			&i.SelectedText,
			&i.AnchorJson,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommentBody = `-- name: UpdateCommentBody :exec
UPDATE comments SET body=$1 WHERE id=$2
`

type UpdateCommentBodyParams struct {
	Body string
	ID   string
}

func (q *Queries) UpdateCommentBody(ctx context.Context, arg UpdateCommentBodyParams) error {
	_, err := q.db.Exec(ctx, updateCommentBody, arg.Body, arg.ID)
	return err
}

const updateCommentStatus = `-- name: UpdateCommentStatus :exec
UPDATE comments SET status=$1, resolved_at=CASE WHEN $1='resolved' THEN now() ELSE NULL END WHERE id=$2
`

type UpdateCommentStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateCommentStatus(ctx context.Context, arg UpdateCommentStatusParams) error {
	_, err := q.db.Exec(ctx, updateCommentStatus, arg.Status, arg.ID)
	return err
}
