// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents WHERE id=$1
`

func (q *Queries) DeleteDocument(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT d.id,d.title,d.current_version_id,u.id AS owner_id,u.email AS owner_email,u.name AS owner_name
FROM documents d JOIN users u ON u.id=d.owner_id WHERE d.id=$1
`

type GetDocumentRow struct {
	ID               string
	Title            string
	CurrentVersionID pgtype.Text
	OwnerID          string
	OwnerEmail       string
	OwnerName        string
}

func (q *Queries) GetDocument(ctx context.Context, id string) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CurrentVersionID,
		&i.OwnerID,
		&i.OwnerEmail,
		&i.OwnerName,
	)
	return i, err
}

const getDocumentGrantRole = `-- name: GetDocumentGrantRole :one
SELECT role FROM resource_grants WHERE resource_type='document' AND resource_id=$1 AND principal_type=$2 AND principal_id=$3 AND revoked_at IS NULL
`

type GetDocumentGrantRoleParams struct {
	ResourceID    string
	PrincipalType string
	PrincipalID   string
}

func (q *Queries) GetDocumentGrantRole(ctx context.Context, arg GetDocumentGrantRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getDocumentGrantRole, arg.ResourceID, arg.PrincipalType, arg.PrincipalID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getDocumentOwnerID = `-- name: GetDocumentOwnerID :one
SELECT owner_id FROM documents WHERE id=$1
`

func (q *Queries) GetDocumentOwnerID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getDocumentOwnerID, id)
	var owner_id string
	err := row.Scan(&owner_id)
	return owner_id, err
}

const getDocumentVersionForUpdate = `-- name: GetDocumentVersionForUpdate :one
SELECT current_version_id, COALESCE((SELECT max(number)+1 FROM versions WHERE document_id=$1),1)::int AS next_number
FROM documents WHERE id=$1 FOR UPDATE
`

type GetDocumentVersionForUpdateRow struct {
	CurrentVersionID pgtype.Text
	NextNumber       int32
}

func (q *Queries) GetDocumentVersionForUpdate(ctx context.Context, documentID string) (GetDocumentVersionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getDocumentVersionForUpdate, documentID)
	var i GetDocumentVersionForUpdateRow
	err := row.Scan(&i.CurrentVersionID, &i.NextNumber)
	return i, err
}

const insertDocument = `-- name: InsertDocument :exec
INSERT INTO documents(id,title,owner_id) VALUES($1,$2,$3)
`

type InsertDocumentParams struct {
	ID      string
	Title   string
	OwnerID string
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) error {
	_, err := q.db.Exec(ctx, insertDocument, arg.ID, arg.Title, arg.OwnerID)
	return err
}

const listDocuments = `-- name: ListDocuments :many
SELECT d.id,d.title,d.current_version_id,u.id AS owner_id,u.email AS owner_email,u.name AS owner_name
FROM documents d JOIN users u ON u.id=d.owner_id
WHERE (d.owner_id=$1 AND $2='user')
   OR EXISTS (
       SELECT 1 FROM resource_grants g
       WHERE g.resource_type='document'
         AND g.resource_id=d.id
         AND g.revoked_at IS NULL
         AND ((g.principal_type=$2 AND g.principal_id=$1) OR g.principal_type='anyone')
   )
ORDER BY d.updated_at DESC
`

type ListDocumentsParams struct {
	OwnerID string
	Column2 interface{}
}

type ListDocumentsRow struct {
	ID               string
	Title            string
	CurrentVersionID pgtype.Text
	OwnerID          string
	OwnerEmail       string
	OwnerName        string
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]ListDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listDocuments, arg.OwnerID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsRow
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CurrentVersionID,
			&i.OwnerID,
			&i.OwnerEmail,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentCurrentVersion = `-- name: UpdateDocumentCurrentVersion :exec
UPDATE documents SET current_version_id=$1, updated_at=now() WHERE id=$2
`

type UpdateDocumentCurrentVersionParams struct {
	CurrentVersionID pgtype.Text
	ID               string
}

func (q *Queries) UpdateDocumentCurrentVersion(ctx context.Context, arg UpdateDocumentCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, updateDocumentCurrentVersion, arg.CurrentVersionID, arg.ID)
	return err
}

const updateDocumentTitle = `-- name: UpdateDocumentTitle :exec
UPDATE documents SET title=$1,updated_at=now() WHERE id=$2
`

type UpdateDocumentTitleParams struct {
	Title string
	ID    string
}

func (q *Queries) UpdateDocumentTitle(ctx context.Context, arg UpdateDocumentTitleParams) error {
	_, err := q.db.Exec(ctx, updateDocumentTitle, arg.Title, arg.ID)
	return err
}
