// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grants.sql

package dbsqlc

import (
	"context"
)

const deleteGrant = `-- name: DeleteGrant :one
UPDATE resource_grants SET revoked_at=now() WHERE id=$1 AND resource_type='document' AND resource_id=$2 AND revoked_at IS NULL
RETURNING id
`

type DeleteGrantParams struct {
	ID         string
	ResourceID string
}

func (q *Queries) DeleteGrant(ctx context.Context, arg DeleteGrantParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteGrant, arg.ID, arg.ResourceID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getGrant = `-- name: GetGrant :one
SELECT id,resource_id,principal_type,principal_id,role,granted_by_user_id FROM resource_grants WHERE id=$1 AND resource_type='document' AND resource_id=$2 AND revoked_at IS NULL
`

type GetGrantParams struct {
	ID         string
	ResourceID string
}

type GetGrantRow struct {
	ID              string
	ResourceID      string
	PrincipalType   string
	PrincipalID     string
	Role            string
	GrantedByUserID string
}

func (q *Queries) GetGrant(ctx context.Context, arg GetGrantParams) (GetGrantRow, error) {
	row := q.db.QueryRow(ctx, getGrant, arg.ID, arg.ResourceID)
	var i GetGrantRow
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Role,
		&i.GrantedByUserID,
	)
	return i, err
}

const listGrants = `-- name: ListGrants :many
SELECT id,principal_type,principal_id,role,granted_by_user_id FROM resource_grants WHERE resource_type='document' AND resource_id=$1 AND revoked_at IS NULL
`

type ListGrantsRow struct {
	ID              string
	PrincipalType   string
	PrincipalID     string
	Role            string
	GrantedByUserID string
}

func (q *Queries) ListGrants(ctx context.Context, resourceID string) ([]ListGrantsRow, error) {
	rows, err := q.db.Query(ctx, listGrants, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGrantsRow
	for rows.Next() {
		var i ListGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalType,
			&i.PrincipalID,
			&i.Role,
			&i.GrantedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGrantRole = `-- name: UpdateGrantRole :one
UPDATE resource_grants SET role=$1 WHERE id=$2 AND resource_type='document' AND resource_id=$3 AND revoked_at IS NULL
RETURNING id,resource_id,principal_type,principal_id,role,granted_by_user_id
`

type UpdateGrantRoleParams struct {
	Role       string
	ID         string
	ResourceID string
}

type UpdateGrantRoleRow struct {
	ID              string
	ResourceID      string
	PrincipalType   string
	PrincipalID     string
	Role            string
	GrantedByUserID string
}

func (q *Queries) UpdateGrantRole(ctx context.Context, arg UpdateGrantRoleParams) (UpdateGrantRoleRow, error) {
	row := q.db.QueryRow(ctx, updateGrantRole, arg.Role, arg.ID, arg.ResourceID)
	var i UpdateGrantRoleRow
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Role,
		&i.GrantedByUserID,
	)
	return i, err
}

const upsertResourceGrant = `-- name: UpsertResourceGrant :one
INSERT INTO resource_grants(id,resource_type,resource_id,principal_type,principal_id,role,granted_by_user_id)
VALUES($1,'document',$2,$3,$4,$5,$6)
ON CONFLICT(resource_type,resource_id,principal_type,principal_id) DO UPDATE SET role=EXCLUDED.role, revoked_at=NULL
RETURNING id
`

type UpsertResourceGrantParams struct {
	ID              string
	ResourceID      string
	PrincipalType   string
	PrincipalID     string
	Role            string
	GrantedByUserID string
}

func (q *Queries) UpsertResourceGrant(ctx context.Context, arg UpsertResourceGrantParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertResourceGrant,
		arg.ID,
		arg.ResourceID,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.Role,
		arg.GrantedByUserID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
