// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CliCredential struct {
	ID         string
	UserID     string
	Name       string
	TokenHash  string
	LastUsedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type Comment struct {
	ID                 string
	DocumentID         string
	CreatedOnVersionID string
	AuthorType         string
	AuthorID           string
	AuthorEmail        string
	AuthorName         string
	Body               string
	SelectedText       string
	AnchorJson         []byte
	Status             string
	CreatedAt          pgtype.Timestamptz
	ResolvedAt         pgtype.Timestamptz
}

type CommentPlacement struct {
	ID          string
	CommentID   string
	VersionID   string
	Status      string
	AnchorJson  []byte
	MatchedText pgtype.Text
	Confidence  float64
	CreatedAt   pgtype.Timestamptz
}

type Document struct {
	ID               string
	Title            string
	OwnerID          string
	CurrentVersionID pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type DocumentWorkspaceEntry struct {
	DocumentID    string
	PrincipalType string
	PrincipalID   string
	AddedAt       pgtype.Timestamptz
}

type OauthState struct {
	ID        string
	Kind      string
	StateJson []byte
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type OwnershipTransfer struct {
	ID               string
	ServiceAccountID string
	FromUserID       string
	ToUserID         string
	InitiatedAt      pgtype.Timestamptz
	AcceptedAt       pgtype.Timestamptz
	Status           string
}

type ResourceGrant struct {
	ID              string
	ResourceType    string
	ResourceID      string
	PrincipalType   string
	PrincipalID     string
	Role            string
	GrantedByUserID string
	CreatedAt       pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
}

type ServiceAccount struct {
	ID              string
	Name            string
	OwnerUserID     string
	CreatedByUserID string
	CreatedAt       pgtype.Timestamptz
	DisabledAt      pgtype.Timestamptz
}

type ServiceAccountKey struct {
	ID               string
	ServiceAccountID string
	Name             string
	TokenHash        string
	LastUsedAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
}

type User struct {
	ID         string
	Email      string
	Name       string
	PictureUrl string
	GoogleSub  pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type Version struct {
	ID              string
	DocumentID      string
	Number          int32
	HtmlBlobKey     string
	Sha256          string
	ParentVersionID pgtype.Text
	CreatedByType   string
	CreatedByID     string
	ChangeSummary   string
	CreatedAt       pgtype.Timestamptz
}
