// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ownership_transfers.sql

package dbsqlc

import (
	"context"
)

const acceptOwnershipTransfer = `-- name: AcceptOwnershipTransfer :one
UPDATE ownership_transfers SET status='accepted',accepted_at=now() WHERE id=$1 AND status='pending'
RETURNING id
`

func (q *Queries) AcceptOwnershipTransfer(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, acceptOwnershipTransfer, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const declineOwnershipTransfer = `-- name: DeclineOwnershipTransfer :one
UPDATE ownership_transfers SET status='declined' WHERE id=$1 AND status='pending' AND (from_user_id=$2 OR to_user_id=$2)
RETURNING id
`

type DeclineOwnershipTransferParams struct {
	ID         string
	FromUserID string
}

func (q *Queries) DeclineOwnershipTransfer(ctx context.Context, arg DeclineOwnershipTransferParams) (string, error) {
	row := q.db.QueryRow(ctx, declineOwnershipTransfer, arg.ID, arg.FromUserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getOwnershipTransferForUpdate = `-- name: GetOwnershipTransferForUpdate :one
SELECT id,service_account_id,from_user_id,to_user_id,status FROM ownership_transfers WHERE id=$1 FOR UPDATE
`

type GetOwnershipTransferForUpdateRow struct {
	ID               string
	ServiceAccountID string
	FromUserID       string
	ToUserID         string
	Status           string
}

func (q *Queries) GetOwnershipTransferForUpdate(ctx context.Context, id string) (GetOwnershipTransferForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOwnershipTransferForUpdate, id)
	var i GetOwnershipTransferForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ServiceAccountID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Status,
	)
	return i, err
}

const insertOwnershipTransfer = `-- name: InsertOwnershipTransfer :exec
INSERT INTO ownership_transfers(id,service_account_id,from_user_id,to_user_id,status) VALUES($1,$2,$3,$4,'pending')
`

type InsertOwnershipTransferParams struct {
	ID               string
	ServiceAccountID string
	FromUserID       string
	ToUserID         string
}

func (q *Queries) InsertOwnershipTransfer(ctx context.Context, arg InsertOwnershipTransferParams) error {
	_, err := q.db.Exec(ctx, insertOwnershipTransfer,
		arg.ID,
		arg.ServiceAccountID,
		arg.FromUserID,
		arg.ToUserID,
	)
	return err
}

const listOwnershipTransfers = `-- name: ListOwnershipTransfers :many
SELECT id,service_account_id,from_user_id,to_user_id,status FROM ownership_transfers WHERE from_user_id=$1 OR to_user_id=$1 ORDER BY initiated_at DESC
`

type ListOwnershipTransfersRow struct {
	ID               string
	ServiceAccountID string
	FromUserID       string
	ToUserID         string
	Status           string
}

func (q *Queries) ListOwnershipTransfers(ctx context.Context, fromUserID string) ([]ListOwnershipTransfersRow, error) {
	rows, err := q.db.Query(ctx, listOwnershipTransfers, fromUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnershipTransfersRow
	for rows.Next() {
		var i ListOwnershipTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceAccountID,
			&i.FromUserID,
			&i.ToUserID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceAccountOwner = `-- name: UpdateServiceAccountOwner :exec
UPDATE service_accounts SET owner_user_id=$1 WHERE id=$2
`

type UpdateServiceAccountOwnerParams struct {
	OwnerUserID string
	ID          string
}

func (q *Queries) UpdateServiceAccountOwner(ctx context.Context, arg UpdateServiceAccountOwnerParams) error {
	_, err := q.db.Exec(ctx, updateServiceAccountOwner, arg.OwnerUserID, arg.ID)
	return err
}
