// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_accounts.sql

package dbsqlc

import (
	"context"
)

const disableServiceAccount = `-- name: DisableServiceAccount :exec
UPDATE service_accounts SET disabled_at=COALESCE(disabled_at,now()) WHERE id=$1
`

func (q *Queries) DisableServiceAccount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, disableServiceAccount, id)
	return err
}

const enableServiceAccount = `-- name: EnableServiceAccount :exec
UPDATE service_accounts SET disabled_at=NULL WHERE id=$1
`

func (q *Queries) EnableServiceAccount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, enableServiceAccount, id)
	return err
}

const getServiceAccount = `-- name: GetServiceAccount :one
SELECT sa.id, sa.name, (sa.disabled_at IS NOT NULL)::bool AS disabled, u.id AS owner_id, u.email AS owner_email, u.name AS owner_name
FROM service_accounts sa
JOIN users u ON u.id = sa.owner_user_id
WHERE sa.id = $1
`

type GetServiceAccountRow struct {
	ID         string
	Name       string
	Disabled   bool
	OwnerID    string
	OwnerEmail string
	OwnerName  string
}

func (q *Queries) GetServiceAccount(ctx context.Context, id string) (GetServiceAccountRow, error) {
	row := q.db.QueryRow(ctx, getServiceAccount, id)
	var i GetServiceAccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Disabled,
		&i.OwnerID,
		&i.OwnerEmail,
		&i.OwnerName,
	)
	return i, err
}

const getServiceAccountByName = `-- name: GetServiceAccountByName :one
SELECT sa.id, sa.name, (sa.disabled_at IS NOT NULL)::bool AS disabled, u.id AS owner_id, u.email AS owner_email, u.name AS owner_name
FROM service_accounts sa
JOIN users u ON u.id = sa.owner_user_id
WHERE sa.name = $1
`

type GetServiceAccountByNameRow struct {
	ID         string
	Name       string
	Disabled   bool
	OwnerID    string
	OwnerEmail string
	OwnerName  string
}

func (q *Queries) GetServiceAccountByName(ctx context.Context, name string) (GetServiceAccountByNameRow, error) {
	row := q.db.QueryRow(ctx, getServiceAccountByName, name)
	var i GetServiceAccountByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Disabled,
		&i.OwnerID,
		&i.OwnerEmail,
		&i.OwnerName,
	)
	return i, err
}

const insertServiceAccount = `-- name: InsertServiceAccount :exec
INSERT INTO service_accounts(id,name,owner_user_id,created_by_user_id) VALUES($1,$2,$3,$3)
`

type InsertServiceAccountParams struct {
	ID          string
	Name        string
	OwnerUserID string
}

func (q *Queries) InsertServiceAccount(ctx context.Context, arg InsertServiceAccountParams) error {
	_, err := q.db.Exec(ctx, insertServiceAccount, arg.ID, arg.Name, arg.OwnerUserID)
	return err
}

const insertServiceAccountKey = `-- name: InsertServiceAccountKey :exec
INSERT INTO service_account_keys(id,service_account_id,name,token_hash) VALUES($1,$2,$3,$4)
`

type InsertServiceAccountKeyParams struct {
	ID               string
	ServiceAccountID string
	Name             string
	TokenHash        string
}

func (q *Queries) InsertServiceAccountKey(ctx context.Context, arg InsertServiceAccountKeyParams) error {
	_, err := q.db.Exec(ctx, insertServiceAccountKey,
		arg.ID,
		arg.ServiceAccountID,
		arg.Name,
		arg.TokenHash,
	)
	return err
}

const listServiceAccountKeys = `-- name: ListServiceAccountKeys :many
SELECT id,name FROM service_account_keys WHERE service_account_id=$1 AND revoked_at IS NULL ORDER BY created_at DESC
`

type ListServiceAccountKeysRow struct {
	ID   string
	Name string
}

func (q *Queries) ListServiceAccountKeys(ctx context.Context, serviceAccountID string) ([]ListServiceAccountKeysRow, error) {
	rows, err := q.db.Query(ctx, listServiceAccountKeys, serviceAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServiceAccountKeysRow
	for rows.Next() {
		var i ListServiceAccountKeysRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceAccounts = `-- name: ListServiceAccounts :many
SELECT sa.id,sa.name,(sa.disabled_at IS NOT NULL)::bool AS disabled,u.id AS owner_id,u.email AS owner_email,u.name AS owner_name
FROM service_accounts sa JOIN users u ON u.id=sa.owner_user_id WHERE sa.owner_user_id=$1 ORDER BY sa.created_at DESC
`

type ListServiceAccountsRow struct {
	ID         string
	Name       string
	Disabled   bool
	OwnerID    string
	OwnerEmail string
	OwnerName  string
}

func (q *Queries) ListServiceAccounts(ctx context.Context, ownerUserID string) ([]ListServiceAccountsRow, error) {
	rows, err := q.db.Query(ctx, listServiceAccounts, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServiceAccountsRow
	for rows.Next() {
		var i ListServiceAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Disabled,
			&i.OwnerID,
			&i.OwnerEmail,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeServiceAccountKey = `-- name: RevokeServiceAccountKey :exec
UPDATE service_account_keys SET revoked_at=now() WHERE service_account_id=$1 AND id=$2
`

type RevokeServiceAccountKeyParams struct {
	ServiceAccountID string
	ID               string
}

func (q *Queries) RevokeServiceAccountKey(ctx context.Context, arg RevokeServiceAccountKeyParams) error {
	_, err := q.db.Exec(ctx, revokeServiceAccountKey, arg.ServiceAccountID, arg.ID)
	return err
}

const serviceAccountExists = `-- name: ServiceAccountExists :one
SELECT EXISTS(SELECT 1 FROM service_accounts WHERE id = $1)::bool
`

func (q *Queries) ServiceAccountExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, serviceAccountExists, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const updateServiceAccountName = `-- name: UpdateServiceAccountName :exec
UPDATE service_accounts SET name=$1 WHERE id=$2
`

type UpdateServiceAccountNameParams struct {
	Name string
	ID   string
}

func (q *Queries) UpdateServiceAccountName(ctx context.Context, arg UpdateServiceAccountNameParams) error {
	_, err := q.db.Exec(ctx, updateServiceAccountName, arg.Name, arg.ID)
	return err
}
