// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: versions.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getVersion = `-- name: GetVersion :one
SELECT id,number,document_id,created_by_type,created_by_id,change_summary,sha256 FROM versions WHERE id=$1
`

type GetVersionRow struct {
	ID            string
	Number        int32
	DocumentID    string
	CreatedByType string
	CreatedByID   string
	ChangeSummary string
	Sha256        string
}

func (q *Queries) GetVersion(ctx context.Context, id string) (GetVersionRow, error) {
	row := q.db.QueryRow(ctx, getVersion, id)
	var i GetVersionRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.DocumentID,
		&i.CreatedByType,
		&i.CreatedByID,
		&i.ChangeSummary,
		&i.Sha256,
	)
	return i, err
}

const getVersionBlobKey = `-- name: GetVersionBlobKey :one
SELECT html_blob_key FROM versions WHERE id=$1
`

func (q *Queries) GetVersionBlobKey(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getVersionBlobKey, id)
	var html_blob_key string
	err := row.Scan(&html_blob_key)
	return html_blob_key, err
}

const insertInitialVersion = `-- name: InsertInitialVersion :exec
INSERT INTO versions(id,document_id,number,html_blob_key,sha256,parent_version_id,created_by_type,created_by_id,change_summary)
VALUES($1,$2,1,$3,$4,NULL,$5,$6,'')
`

type InsertInitialVersionParams struct {
	ID            string
	DocumentID    string
	HtmlBlobKey   string
	Sha256        string
	CreatedByType string
	CreatedByID   string
}

func (q *Queries) InsertInitialVersion(ctx context.Context, arg InsertInitialVersionParams) error {
	_, err := q.db.Exec(ctx, insertInitialVersion,
		arg.ID,
		arg.DocumentID,
		arg.HtmlBlobKey,
		arg.Sha256,
		arg.CreatedByType,
		arg.CreatedByID,
	)
	return err
}

const insertVersion = `-- name: InsertVersion :exec
INSERT INTO versions(id,document_id,number,html_blob_key,sha256,parent_version_id,created_by_type,created_by_id,change_summary)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type InsertVersionParams struct {
	ID              string
	DocumentID      string
	Number          int32
	HtmlBlobKey     string
	Sha256          string
	ParentVersionID pgtype.Text
	CreatedByType   string
	CreatedByID     string
	ChangeSummary   string
}

func (q *Queries) InsertVersion(ctx context.Context, arg InsertVersionParams) error {
	_, err := q.db.Exec(ctx, insertVersion,
		arg.ID,
		arg.DocumentID,
		arg.Number,
		arg.HtmlBlobKey,
		arg.Sha256,
		arg.ParentVersionID,
		arg.CreatedByType,
		arg.CreatedByID,
		arg.ChangeSummary,
	)
	return err
}

const listVersions = `-- name: ListVersions :many
SELECT id,number,document_id,created_by_type,created_by_id,change_summary,sha256 FROM versions WHERE document_id=$1 ORDER BY number
`

type ListVersionsRow struct {
	ID            string
	Number        int32
	DocumentID    string
	CreatedByType string
	CreatedByID   string
	ChangeSummary string
	Sha256        string
}

func (q *Queries) ListVersions(ctx context.Context, documentID string) ([]ListVersionsRow, error) {
	rows, err := q.db.Query(ctx, listVersions, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVersionsRow
	for rows.Next() {
		var i ListVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.DocumentID,
			&i.CreatedByType,
			&i.CreatedByID,
			&i.ChangeSummary,
			&i.Sha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
