package bots

// Wordlists for generating bot addresses like n8n-prod@brave.otter.bot.
// Curated for: pronounceable, friendly, single-token, all lowercase ASCII,
// no offensive overlap, no rude homophones.

var adjectives = []string{
	"agile", "amber", "amused", "ancient", "arctic", "ardent", "artful",
	"bold", "brave", "breezy", "bright", "brisk", "bubbly", "busy",
	"calm", "candid", "chatty", "cheerful", "cheery", "civic", "classic", "clever",
	"comet", "cosmic", "cozy", "crafty", "crimson", "crisp", "curious", "cuddly",
	"daring", "dapper", "dawn", "dazzled", "dear", "deft", "dewy", "diligent",
	"dizzy", "dreamy", "drift", "dusky", "dynamic",
	"eager", "earnest", "easy", "echo", "elated", "elder", "electric", "elegant",
	"emerald", "epic", "eternal", "ever",
	"fabled", "faithful", "fancy", "fearless", "fern", "festive", "fiery", "fine",
	"flashy", "fleet", "fluffy", "fond", "forest", "frosty", "funky",
	"gallant", "gentle", "ginger", "glad", "gleeful", "glinty", "golden", "graceful",
	"grand", "great", "grit",
	"happy", "hardy", "harvest", "hazel", "hearty", "hidden", "honest", "humble", "humming",
	"icy", "ideal", "indigo", "inky", "iron", "ivory",
	"jade", "jolly", "jovial", "joyful", "jumpy",
	"keen", "kind", "kindred",
	"lake", "lavender", "lazy", "lemon", "light", "lively", "lonely", "lucky", "lush",
	"mango", "marble", "merry", "mighty", "mild", "minty", "misty", "modest",
	"moonlit", "mossy",
	"navy", "nimble", "noble", "north",
	"oaken", "ocean", "olive", "onyx", "opal",
	"pacific", "patient", "peach", "peppy", "pine", "plucky", "plush", "polar", "polite",
	"prairie", "pristine", "proud", "prudent",
	"quartz", "quick", "quiet", "quirky",
	"radiant", "rapid", "ready", "rebel", "regal", "river", "rosy", "royal", "rugged",
	"sage", "salty", "sandy", "sapphire", "savvy", "scarlet", "shady", "shiny", "silver",
	"silky", "simple", "sleek", "slick", "smart", "smiling", "snowy", "solid", "sonic",
	"sparkly", "spiced", "spry", "stalwart", "starry", "steady", "stellar", "stoic",
	"storm", "sturdy", "sunny", "sunset", "swift",
	"tame", "tangy", "tender", "thrifty", "tidy", "tiny", "topaz", "trusty", "twilight",
	"upbeat", "urban",
	"velvet", "verdant", "vibrant", "vintage", "violet", "vivid",
	"warm", "wavy", "whimsy", "windy", "winsome", "witty", "wise", "wooden", "woolly",
	"yellow", "yonder",
	"zany", "zealous", "zen", "zesty",
}

var nouns = []string{
	"acorn", "alder", "anchor", "antler", "apple", "arrow", "ash", "aspen", "atlas",
	"badger", "bagel", "banyan", "barrel", "bay", "beacon", "bear", "beaver", "beetle",
	"bison", "blossom", "boulder", "branch", "breeze", "brook", "buffalo", "bumble",
	"cactus", "camel", "canyon", "cardinal", "caribou", "cedar", "chai", "chestnut",
	"chime", "cinder", "cloud", "clover", "cocoa", "comet", "compass", "conch", "coral",
	"cove", "crane", "creek", "crocus", "cypress",
	"daisy", "dapple", "dawn", "deer", "delta", "dewdrop", "dolphin", "dove", "dragonfly",
	"drum", "duckling", "dune",
	"eagle", "echo", "egret", "ember", "emu", "ermine",
	"falcon", "fawn", "feather", "fern", "ferret", "ficus", "field", "finch", "firefly",
	"fjord", "flame", "fleece", "flute", "fog", "fox", "frog", "frost",
	"galaxy", "garnet", "gazelle", "geyser", "glacier", "glow", "goose", "grackle",
	"granite", "grove", "gust",
	"harbor", "harvest", "hawk", "haze", "hazel", "heron", "hickory", "hollow", "horizon",
	"hummingbird",
	"icicle", "iguana", "iris", "island", "ivory", "ivy",
	"jasmine", "jay", "jellyfish", "juniper",
	"kayak", "kelp", "kestrel", "kiwi", "knot", "koala",
	"lagoon", "lantern", "larch", "lark", "lavender", "leaf", "ledger", "lemur", "lichen",
	"lighthouse", "lily", "linden", "lobster", "lotus", "lupine",
	"magnolia", "mango", "maple", "marble", "marmot", "marsh", "meadow", "meander",
	"meridian", "meteor", "mist", "moose", "mosaic", "moss", "mountain",
	"nebula", "needle", "newt", "nimbus", "north", "nova",
	"oak", "oasis", "ocean", "octopus", "olive", "opal", "orchid", "osprey", "otter",
	"owl", "ox", "oyster",
	"panda", "panther", "papyrus", "parsley", "patch", "peach", "pebble", "pegasus",
	"pelican", "penguin", "petal", "pier", "pine", "pinecone", "piper", "pixie", "plum",
	"pollen", "pond", "poplar", "porcupine", "prairie", "puffin", "pumpkin", "puzzle",
	"quail", "quartz", "quill", "quokka",
	"rabbit", "raccoon", "rapid", "raven", "redwood", "reef", "ridge", "river", "robin",
	"rook", "rose", "rune",
	"salmon", "sapphire", "sassafras", "savanna", "scout", "seal", "sequoia", "shore",
	"shrub", "skipper", "sloth", "snail", "snowdrop", "sparrow", "spectre", "spruce",
	"squirrel", "starfish", "stoat", "stork", "stream", "summit", "surf", "swallow",
	"swan", "sycamore",
	"talon", "tangerine", "tapir", "teal", "thicket", "thistle", "thrush", "tide",
	"tiger", "topaz", "tortoise", "totem", "trail", "tulip", "tumble", "turtle", "twig",
	"umbra",
	"valley", "vane", "vapor", "violet", "vista", "vortex", "vulcan",
	"wagon", "walnut", "warbler", "wave", "weasel", "whale", "wheat", "whistle", "willow",
	"wisp", "wolverine", "wombat", "woodpecker", "wren",
	"xenia",
	"yarrow", "yew",
	"zephyr", "zinnia",
}
